apiVersion: v1
kind: Pod
metadata:
  name: go-web-app
  labels:
    app: go-web
spec:
  containers:
  - name: web-server
    image: k8s-day1:v2  # v2 uses alpine base (has shell for kubectl exec debugging)
    imagePullPolicy: Never # Critical for local k3d testing without registry
    ports:
    - containerPort: 8080
    env:
    - name: PORT
      value: "8080"
